FILE(MAKE_DIRECTORY "/home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs" )
FILE(GLOB_RECURSE FOR_DEL /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/* )
#message("delete files from /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/ : ${FOR_DEL}")
if( FOR_DEL )
	FILE(REMOVE ${FOR_DEL})
endif()
execute_process(COMMAND /home/victor/cmsvt_mbzirc/devel/.private/decision_making_parser/lib/decision_making_parser/decision_making_parser -pe -xml -dot -src "/home/victor/cmsvt_mbzirc/src/decision_making_tutorial" -dst "/home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs" -f "/home/victor/cmsvt_mbzirc/src/decision_making_tutorial/src/stateMachChal3.cpp:" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/ /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.scxml /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.btxml  /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.taoxml)
message("   -- Created XML files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.scxml /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.btxml /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.taoxml)
execute_process(COMMAND "python" /home/victor/cmsvt_mbzirc/devel/.private/decision_making_parser/lib/decision_making_parser/decision_making_xml_parser.py -i "/home/victor/cmsvt_mbzirc/src/decision_making_tutorial" "/home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs" "${CREATED_FILES_ABS}" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/ /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.dot /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.xot)
message("   -- Created DOT files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.dot)
foreach( f ${CREATED_FILES_ABS} )
	execute_process(COMMAND "dot" -q1 -Tgif -o${f}.gif  ${f} RESULT_VARIABLE rv)
endforeach()
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/ /home/victor/cmsvt_mbzirc/devel/.private/decision_making_tutorial/share/decision_making_tutorial/graphs/*.gif)
message("   -- Created GIF files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
