arena:
  angle: 0.0
  x_length: 60.0
  y_length: 90.0
landing_zone:
  x_length: 10.0
  y_length: 10.0
  x_offset: -25.0
  y_offset: 0.0
drop_zone:
  x_length: 10.0
  y_length: 10.0
  x_offset: 0.0
  y_offset: -25.0
hexacopter:
  yaw_offset: 0.098
